import { Geist, Geist_Mono } from "next/font/google";
import { StackProvider, StackTheme } from "@stackframe/stack";
import {stackServerApp} from "@/stack";
import "./globals.css";
import ConvexClientProvider from "@/app/ConvexClientProvider";
import ClientProviders from "@/app/ClientProviders";
import {Toaster} from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Canva - создай то что хочешь",
  description: "canva Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><StackProvider app={stackServerApp}>  <StackTheme>
          {/* Put all client logic in ClientProviders */}
          <ConvexClientProvider>
              {children}
              <Toaster/>
          </ConvexClientProvider>
      </StackTheme></StackProvider></body>
    </html>
  );
}
